"""
Django settings for letsrace project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#5avbtnbsu4-))u-lddtuvxhnf#%2p9x*cvjr3pmna^tvk7_6^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.compute.amazonaws.com', '127.0.0.1',
                 'localhost', '43.201.100.201', '0.0.0.0']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',
    'django.contrib.staticfiles',

    'base.apps.BaseConfig',

    'rest_framework',

    "corsheaders",

    'debug_toolbar',
    'mathfilters',
    'django.contrib.humanize',

]

AUTH_USER_MODEL = 'base.User'

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",

    'django.middleware.security.SecurityMiddleware',

    "corsheaders.middleware.CorsMiddleware",

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = 'letsrace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'letsrace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# [ 1 ] : 사용할 엔진 설정. 그대로 두면 됨
# [ 2 ] : 연동할 MySQL의 데이터베이스 이름
# [ 3 ] : DB 접속 계정명
# [ 4 ] : 해당 DB 접속 계정 비밀번호
# [ 5 ] : 실제 DB 주소, 따로 설정 안했으면 그대로 두면 됨
# [ 6 ] : 포트번호, 따로 설정 안했으면 그대로 두면 됨

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # [1]
        'NAME': 'The1',                         # [2]
        'USER': 'letslove',                     # [3]
        'PASSWORD': 'Ruddksp!23',               # [4]
        'HOST': 'super007.synology.me',         # [5]
        'PORT': '3307',                         # [6]
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',   # [1]
#         'NAME': 'The1',                         # [2]
#         'USER': 'letslove',                     # [3]
#         'PASSWORD': 'Ruddksp!23',               # [4]
#         # [5]
#         'HOST': 'database-1.c35iunxhbvd4.ap-northeast-2.rds.amazonaws.com',
#         # 'HOST': 'thethe9-aws.c35iunxhbvd4.ap-northeast-2.rds.amazonaws.com',
#         'PORT': '3306',                         # [6]
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ko-KR'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_ROOT = '/tmp/.static_root'       # EC2 폴더권한문제 방지 nginx
STATIC_URL = 'static/'
MEDIA_URL = '/images/'

# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_ROOT = BASE_DIR / 'static/images'
KRAFILE_ROOT = BASE_DIR / 'kradata'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
