# Generated by Django 4.0.5 on 2025-12-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_precord_rec011_exp011_alloc1r_exp011_alloc3r_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='exp011',
        #     name='m_rank',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011',
        #     name='m_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
    ]
