# Generated by Django 4.0.5 on 2025-12-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_exp011_m_rank_exp011_m_score'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='exp011s1',
        #     name='m_rank',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s1',
        #     name='m_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s2',
        #     name='m_rank',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s2',
        #     name='m_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
    ]
