# Generated by Django 4.0.5 on 2025-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_exp011s1_m_rank_exp011s1_m_score_exp011s2_m_rank_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='exp011',
        #     name='comment_dh',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011',
        #     name='dh_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011',
        #     name='f_rank',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011',
        #     name='f_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011',
        #     name='trusr_label',
        #     field=models.CharField(blank=True, max_length=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011',
        #     name='trust_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s1',
        #     name='comment_dh',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s1',
        #     name='dh_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s1',
        #     name='f_rank',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s1',
        #     name='f_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s1',
        #     name='trusr_label',
        #     field=models.CharField(blank=True, max_length=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s1',
        #     name='trust_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s2',
        #     name='comment_dh',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s2',
        #     name='dh_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s2',
        #     name='f_rank',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s2',
        #     name='f_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s2',
        #     name='trusr_label',
        #     field=models.CharField(blank=True, max_length=10, null=True),
        # ),
        # migrations.AddField(
        #     model_name='exp011s2',
        #     name='trust_score',
        #     field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        # ),
    ]
