# Generated by Django 4.0.5 on 2022-07-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_expect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('wdate', models.DateTimeField(primary_key=True, serialize=False)),
                ('w_avg', models.IntegerField(blank=True, null=True)),
                ('w_fast', models.IntegerField(blank=True, null=True)),
                ('w_slow', models.IntegerField(blank=True, null=True)),
                ('w_recent3', models.IntegerField(blank=True, null=True)),
                ('w_recent5', models.IntegerField(blank=True, null=True)),
                ('w_convert', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weight',
                'managed': False,
            },
        ),
    ]
