# Generated by Django 4.0.5 on 2022-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp010',
            fields=[
                ('rcity', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('rdate', models.CharField(max_length=8)),
                ('rno', models.IntegerField()),
                ('rday', models.CharField(blank=True, max_length=2, null=True)),
                ('rseq', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('rcount', models.CharField(blank=True, max_length=2, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('dividing', models.CharField(blank=True, max_length=20, null=True)),
                ('rname', models.CharField(blank=True, max_length=40, null=True)),
                ('rcon1', models.CharField(blank=True, max_length=20, null=True)),
                ('rcon2', models.CharField(blank=True, max_length=20, null=True)),
                ('rtime', models.CharField(blank=True, max_length=5, null=True)),
                ('r1award', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('r2award', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('r3award', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('r4award', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('r5award', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sub1award', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sub2award', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sub3award', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('cflag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'exp010',
                'managed': False,
            },
        ),
    ]
