# Generated by Django 4.0.5 on 2025-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_exp010_r_overview_exp011_alloc1r_exp011_alloc3r_and_more'),
    ]

    operations = []

