# Generated by Django 4.0.5 on 2022-07-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_exp010_exp011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racing',
            fields=[
                ('rcity', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('rdate', models.CharField(max_length=8)),
                ('rno', models.IntegerField()),
                ('rday', models.CharField(blank=True, max_length=2, null=True)),
                ('rseq', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('rcount', models.CharField(blank=True, max_length=2, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('dividing', models.CharField(blank=True, max_length=20, null=True)),
                ('rname', models.CharField(blank=True, max_length=40, null=True)),
                ('rcon1', models.CharField(blank=True, max_length=20, null=True)),
                ('rcon2', models.CharField(blank=True, max_length=20, null=True)),
                ('rtime', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'racing',
                'managed': False,
            },
        ),
    ]
